// sdk-integration-examples/web-sdk/react/flow-example/src/components/Details/Details.tsx
import "./Details.css";

export const Details = ({
  details,
  onContinue,
  onDone,
}: {
  details: any[];
  onContinue: () => void;
  onDone: () => void;
}) => {
  const fields = [];

  const order = [
    "full_name",
    "given_name",
    "first_name",
    "middle_name",
    "last_name",
    "document_number",
    "birth_date",
    "expiry_date",
    "document_id",
  ];

  details.sort(function (a: any, b: any) {
    const indexA = order.indexOf(a.fieldName);
    const indexB = order.indexOf(b.fieldName);

    if (indexA === -1) return 1;
    if (indexB === -1) return -1;

    return indexA - indexB;
  });

  for (let i = 0; i < details.length; i++) {
    const field = details[i];
    fields.push({
      label: field.fieldName.replace(/_/g, " "),
      name: field.fieldName,
      value: field.fieldValue,
    });
  }

  return (
    <div className="details">
      <div className="details-header">
        <h4 className="details-header-title">Confirm your details</h4>
      </div>

      <div className="details-content">
        <div className="details-section-title">Personal Details</div>
        {fields.map((field) => (
          <div key={field.name} className="details-form-control">
            <label className="details-form-label">{field.label}</label>
            <input
              className="details-form-input"
              disabled
              type="text"
              value={field.value}
            />
          </div>
        ))}

        <div className="details-consent-checkbox">
          <input type="checkbox" id="consent" />
          <p className="details-consent-text">
            This is where we add the main terms and conditions consent checkbox
            text
          </p>
        </div>

        <button className="details-submit-button" onClick={onContinue}>
          Continue
        </button>
        <button className="details-submit-button" onClick={onDone}>Done</button>
      </div>
    </div>
  );
};

// sdk-integration-examples/web-sdk/angular/id-scan/src/app/details/details.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  selector: "app-details",
  standalone: true,
  imports: [],
  templateUrl: "./details.component.html",
  styleUrl: "./details.component.scss",
})
export class DetailsComponent {
  @Input() details: any = [];
  @Output() onClose = new EventEmitter<void>();

  onGetFields() {
    const fields = [];

    const order = [
      "full_name",
      "given_name",
      "first_name",
      "middle_name",
      "last_name",
      "document_number",
      "birth_date",
      "expiry_date",
      "document_id",
    ];

    this.details.sort(function (a: any, b: any) {
      var indexA = order.indexOf(a.fieldName);
      var indexB = order.indexOf(b.fieldName);

      // If one of the field names is not present in the order array,
      // it should come after the ones that are present.
      if (indexA === -1) return 1;
      if (indexB === -1) return -1;

      return indexA - indexB;
    });

    for (let i = 0; i < this.details.length; i++) {
      const field = this.details[i];
      fields.push({
        label: field.fieldName.replace(/_/g, " "),
        name: field.fieldName,
        value: field.fieldValue,
      });
    }
    return fields;
  }
}

<div class="details">
  <div class="form">
    <h4>Extracted details</h4>
    @for (field of onGetFields(); track field.name) {
    <div [id]="field.name" class="form-control">
      <label [htmlFor]="field.name">{{ field.label }}</label>
      <input
        disabled
        type="text"
        [name]="field.name"
        [value]="field.value"
        [id]="field.name"
      />
    </div>
    }
  </div>

  <footer>
    <button (click)="handleClose()">Close</button>
  </footer>
</div>
